import {createHash} from 'node:crypto';
import {canAccessPost} from '@/lib/access';
import {streamFile,privateFile,validPath,allowedMedia} from '@/lib/media';
import {identity,isOwner,entitled,database,settings,sameOrigin} from '@/lib/store';
import {stripe,syncCustomer} from '@/lib/payments';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(r:Request,{params}:{params:Promise<{path:string[]}>}){try{const {path}=await params;const db=database();if(path[0]==='posts'&&path[1]){const post=await db.prepare('SELECT * FROM posts WHERE id=?').bind(path[1]).first<any>();if(!post)return json({error:'This offering could not be found.'},404);if(!canAccessPost(post.audience,!!await identity(),await entitled()))return json({error:'This offering requires all access. Get your pass to unlock the collection.'},403);const {asset,...safe}=post;return json(safe);}
if(path[0]==='media'&&path[1]){const p=await db.prepare('SELECT * FROM posts WHERE id=?').bind(path[1]).first<any>();if(!p?.asset)return json({error:'Media not found.'},404);if(!canAccessPost(p.audience,!!await identity(),await entitled()))return json({error:'Membership required.'},403);return streamFile(p.asset,r);}return json({error:'Not found.'},404);}catch(e){console.error('Content read failed',e);return json({error:'The collection is unavailable. Please try again.'},503);}}
export async function POST(r:Request,{params}:{params:Promise<{path:string[]}>}){const {path}=await params;
try{if(path[0]==='webhook'){const config=settings();if(!config.STRIPE_WEBHOOK_SECRET)return json({error:'Webhook not configured.'},503);let event;try{event=await stripe().webhooks.constructEventAsync(await r.text(),r.headers.get('stripe-signature')||'',config.STRIPE_WEBHOOK_SECRET,undefined,undefined);}catch{return json({error:'Invalid signature.'},400);}const supported=['checkout.session.completed','checkout.session.async_payment_succeeded','customer.subscription.created','customer.subscription.updated','customer.subscription.deleted','invoice.paid','invoice.payment_failed'];if(supported.includes(event.type)){const object=event.data.object as any;const customer=typeof object.customer==='string'?object.customer:object.customer?.id;if(customer)await syncCustomer(customer);}return json({received:true});}
if(!sameOrigin(r))return json({error:'Invalid request origin.'},403);const u=await identity();if(!u)return json({error:'Please sign in to continue.'},401);const db=database();
if(path[0]==='checkout'){const config=settings();if(!config.STRIPE_SECRET_KEY||!config.STRIPE_PRICE_ID||!config.STRIPE_WEBHOOK_SECRET)return json({error:'Membership opens soon. Please check back.'},503);if(await entitled())return json({error:'Your membership is already active.'},409);const s=stripe();const price=await s.prices.retrieve(config.STRIPE_PRICE_ID);if(price.unit_amount!==299||price.currency!=='usd'||price.recurring?.interval!=='month'||price.recurring.interval_count!==1||!price.active)throw Error('Membership price configuration is invalid.');await db.prepare('INSERT INTO members(id,email) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email').bind(u.userId,u.email).run();let member=await db.prepare('SELECT customer FROM members WHERE id=?').bind(u.userId).first<{customer:string|null}>();if(!member?.customer){const customer=await s.customers.create({email:u.email,name:u.fullName||undefined},{idempotencyKey:'sarafina-customer-'+u.userId});await db.prepare('UPDATE members SET customer=? WHERE id=?').bind(customer.id,u.userId).run();member={customer:customer.id};}await syncCustomer(member.customer!);if(await entitled())return json({error:'Your membership is already active. Refresh to see your collection.'},409);const origin=config.SITE_URL;if(!origin)throw Error('Site URL missing');const session=await s.checkout.sessions.create({mode:'subscription',integration_identifier:'sarafina_membership_abcdefgh',customer:member.customer!,line_items:[{price:config.STRIPE_PRICE_ID,quantity:1}],success_url:origin+'/welcome',cancel_url:origin+'/#membership'},{idempotencyKey:'sarafina-checkout-'+u.userId+'-'+Math.floor(Date.now()/300000)});return json({url:session.url});}
if(path[0]==='portal'){const member=await db.prepare('SELECT customer FROM members WHERE id=?').bind(u.userId).first<{customer:string|null}>();if(!member?.customer)return json({error:'No billing account is connected yet.'},404);const session=await stripe().billingPortal.sessions.create({customer:member.customer,return_url:settings().SITE_URL+'/'});return json({url:session.url});}
if(path[0]==='publish'){if(!await isOwner())return json({error:'Creator access required.'},403);const form=await r.formData();const title=String(form.get('title')||'').trim(),body=String(form.get('body')||'').trim(),kind=String(form.get('kind')),audience=String(form.get('audience'));const preview=String(form.get('preview')||'').trim();if(preview.length>400)return json({error:'Keep the public preview under 400 characters.'},400);if(!title||title.length>180||!body||body.length>20000||!['music','journal'].includes(kind)||!['public','free','members'].includes(audience))return json({error:'Add a title and a note, then choose the content type and access.'},400);let id=crypto.randomUUID() as string;let asset=String(form.get('asset')||'')||null;let mime:string|null=null;if(asset){if(!validPath(asset))return json({error:'Invalid media upload.'},400);const upload=await db.prepare('SELECT owner FROM uploads WHERE pathname=?').bind(asset).first<{owner:string}>();if(upload?.owner!==u.userId)return json({error:'This upload does not belong to you.'},403);const file=await privateFile(asset);if(file.size>50*1024*1024||!allowedMedia.includes(file.contentType))return json({error:'Unsupported file. Use supported audio, video or image under 50 MB.'},400);mime=file.contentType;id=createHash('sha256').update(u.userId+':'+asset).digest('hex');}try{await db.prepare('INSERT INTO posts(id,title,body,preview,kind,audience,asset,mime,published) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,title,body,preview,kind,audience,asset,mime,Math.floor(Date.now()/1000)).run();}catch(e){throw e;}return json({id},201);}return json({error:'Not found.'},404);
}catch(e){console.error('Membership operation failed',e);return json({error:'We could not complete that. Please try again in a moment.'},503);}}

