"use client";
import { useState,useEffect } from 'react';
import MemberControls from './member-controls';
import { Music2,Lock,Headphones,Sparkles,Check,Flower2 } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import {canAccessPost} from '@/lib/access';
type Post={id:string;title:string;kind:string;audience:string;published:number;preview?:string;body?:string;mime?:string};
export default function Home({signedIn,active,owner,ready,authReady,posts,unavailable}:{signedIn:boolean;active:boolean;owner:boolean;ready:boolean;authReady:boolean;posts:Post[];unavailable:boolean}){
 const [tab,setTab]=useState('all'),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Post|null>(null),[locked,setLocked]=useState<Post|null>(null),[busy,setBusy]=useState(false);
 const freeJoin=()=>{if(!authReady){setNotice('Free membership is opening soon. You’ll be able to create an account without a payment card.');return;}location.href='/sign-up';};
 const join=async()=>{if(!ready||!authReady){setNotice('The inner circle is opening soon. Membership will be $2.99 per month, with the music archive and new offerings every week.');return;}if(!signedIn){location.href='/sign-in?redirect_url=%2F%23membership';return;}setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url;}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
 const open=async(p:Post)=>{if(!canAccessPost(p.audience,signedIn,active)){setLocked(p);return;}try{const r=await fetch('/api/posts/'+p.id);const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(d);}catch(e){setNotice((e as Error).message);}};
 const portal=async()=>{try{const r=await fetch('/api/portal',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url;}catch(e){setNotice((e as Error).message);}};
 const freeSongs=posts.filter(p=>p.audience==='public'&&p.kind==='music'&&p.mime?.startsWith('audio/')).slice(0,2);
 const label=(p:Post)=>p.audience==='public'?'FREE TO ENJOY':p.audience==='free'?'FREE MEMBERS':'INNER CIRCLE';
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx)return;const a=new AbortController();Promise.resolve(ctx.registerTool({name:'browse_sarafina_library',description:'Filter the visible library by all, music, or journal.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['all','music','journal']}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async({category}:{category:string})=>{if(!['all','music','journal'].includes(category))throw Error('Invalid category');setTab(category);return {category,count:posts.filter(p=>category==='all'||p.kind===category).length};}},{signal:a.signal})).catch(()=>{});return ()=>a.abort();},[posts]);
 return <><header><a className="brand brand-message" href="/" aria-label="Music connects us — Sarafina Ethereal home">Music connects us</a><nav><a href="#listen">Listen</a><a href="#library">The collection</a><a href="#membership">Join the circle</a>{owner&&<a href="/studio">Creator studio</a>}{signedIn?<MemberControls/>:<a href="/sign-in">Sign in</a>}</nav></header>
 <main><section className="hero"><div className="portrait" role="img" aria-label="Sarafina Ethereal wearing an ornate floral and pearl crown"/><div className="hero-copy"><div className="hero-glass glass-panel"><p className="eyebrow">A LITTLE CLOSER TO THE MUSIC</p><h1>Sarafina<br/><i>Ethereal.</i></h1><p className="intro">Soulful. Visceral. Unfiltered.<br/>For the ache. The release. The things we can’t quite say.</p><a className="button" href={active?'#library':'#listen'}>{active?'Enter your collection':'Listen for free'} <Headphones size={18}/></a><a className="text-link" href="#membership">{active?'Your place in the circle':'If it moves you, come closer · $2.99/month'}</a></div></div><div className="hero-bottom"><span>ORIGINAL MUSIC · INTIMATE MOMENTS</span><span>AN OFFERING, EVERY WEEK</span></div></section>
 <section className={'listen section'+(freeSongs.length?'':' is-empty')} id="listen"><div className="section-head"><div><p className="eyebrow">YOUR FIRST LISTEN</p><h2>Let it move you.</h2></div><p>A little of my soul, freely shared.<br/>No account. Just listen.</p></div>{freeSongs.length?<div className="listen-grid">{freeSongs.map(p=><article className="song-card" key={p.id}><div className="song-heading"><Music2 size={28}/><div><p className="post-meta">FREE SONG</p><h3>{p.title}</h3></div></div>{p.preview&&<p>{p.preview}</p>}<audio controls preload="none" aria-label={'Listen to '+p.title} src={'/api/media/'+p.id}/><button className="text-link" onClick={()=>open(p)}>Read the story behind the song</button></article>)}</div>:<div className="listening-soon"><Music2 size={28}/><h3>A little soul is on its way.</h3><p>The first songs will live here, freely shared. Come as you are.</p><a className="text-link" href="#membership">Explore free and paid membership</a></div>}{freeSongs.length>0&&<div className="listen-invitation"><p>If a song finds something in you, stay a little.</p><a href="#membership" className="text-link">Find your place in the circle →</a></div>}</section>
 <section className={'library section'+(posts.length?'':' is-empty')} id="library"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Stay for a while.</h2></div><p>Songs I’ve lived. Stories still unfolding.<br/>The music, and the life inside it.</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="collection-tabs"><TabsTrigger value="all">Everything</TabsTrigger><TabsTrigger value="music">Music</TabsTrigger><TabsTrigger value="journal">Notes & moments</TabsTrigger></TabsList>{['all','music','journal'].map(t=><TabsContent key={t} value={t}><div className="post-grid">{posts.filter(p=>t==='all'||p.kind===t).map(p=><button className="post" key={p.id} onClick={()=>open(p)}><div className={'post-art '+p.kind}>{p.kind==='music'?<Music2 size={42}/>:<Flower2 size={42}/>}<span>{!canAccessPost(p.audience,signedIn,active)&&<Lock size={13}/>} {label(p)}</span></div><p className="post-meta">{p.kind==='music'?'MUSIC':'NOTES & MOMENTS'} · {new Date(p.published*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'})}</p><h3>{p.title}</h3>{p.preview&&<p className="post-preview">{p.preview}</p>}<span className="post-action">{canAccessPost(p.audience,signedIn,active)?'Explore this offering →':p.audience==='free'?'Join free to open →':'Unlock with the inner circle →'}</span></button>)}</div>{posts.filter(p=>t==='all'||p.kind===t).length===0&&<div className="empty"><Sparkles size={26}/><h3>Something real is taking shape.</h3><p>{unavailable?'Free songs, personal notes, and members-only offerings will appear here as the circle opens.':'The first offerings will appear here. There’s a place for you in the circle.'}</p></div>}</TabsContent>)}</Tabs><div className="collection-note"><Headphones size={20}/><p>From my tender places to yours.</p><span>Music · Process · Presence</span></div></section>
 <section className="membership section" id="membership"><div className="membership-copy glass-panel"><p className="eyebrow">FIND YOUR PLACE</p><h2>Come closer.<br/><i>Bring all of you.</i></h2><p>Some songs arrive like a confession. Some feel like coming home. This is where I share them—and the messy, human moments in between. Your membership helps me keep making music that tells the truth.</p></div><div className="membership-options"><div className="membership-card free-card"><h3>Stay a little.</h3><p className="price">Free <span>/ always</span></p><ul>{['The free song selection','Public notes and moments','Offerings shared with free members'].map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul>{signedIn?<a className="button" href="#library">Explore your free offerings</a>:<button className="button" onClick={freeJoin}>Join for free</button>}<p className="fine">{signedIn?'Your account includes access to free offerings.':'No payment card. No pressure. Come closer when you’re ready.'}</p></div><div className="membership-card paid-card"><p className="eyebrow">THE INNER CIRCLE</p><Flower2 size={33}/><h3>The songs. The stories. The soul.</h3><p className="price">$2.99 <span>/ month</span></p><ul>{['Everything shared for free','Full access to the music archive','New music and exclusive releases','Fresh offerings every week','The raw moments behind the music'].map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul>{active?<button className="button" onClick={portal}>Manage membership</button>:<button className="button" onClick={join} disabled={busy}>{busy?'Opening checkout…':signedIn?'Unlock the inner circle':'Join the inner circle'}</button>}<p className="fine">{ready&&authReady?'$2.99 billed monthly. Cancel anytime. Secure checkout with Stripe.':'Opening soon · $2.99/month · Cancel anytime.'}</p></div></div></section>
 <section className="closing"><div className="closing-glass glass-panel"><p className="eyebrow">ETHEREAL, BUT ALWAYS HUMAN.</p><p>For the ones who feel it all.</p><Flower2 size={25}/></div></section></main><footer><a className="brand" href="/"><span className="brand-prefix">Ms.</span> Ethereal</a><span>Independent music. A little soul between us.</span><small>© {new Date().getFullYear()} Sarafina Ethereal</small></footer>
 <Dialog open={!!notice} onOpenChange={()=>setNotice('')}><DialogContent className="modal"><DialogHeader><DialogTitle>A little note</DialogTitle><DialogDescription>{notice}</DialogDescription></DialogHeader></DialogContent></Dialog>
 <Dialog open={!!locked} onOpenChange={()=>setLocked(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{locked?.title}</DialogTitle><DialogDescription>{locked?.preview||'A song, a story, a little more of me.'}</DialogDescription></DialogHeader><div className="unlock-panel"><Lock size={24}/><h3>{locked?.audience==='free'?'Something I saved for you':'There’s more to feel.'}</h3><p>{locked?.audience==='free'?'Create a free account to open this offering. No payment card needed.':'Join for $2.99/month to open this offering, the full archive, and fresh content every week.'}</p><button className="button" disabled={busy} onClick={()=>{const audience=locked?.audience;setLocked(null);if(audience==='free')freeJoin();else void join();}}>{locked?.audience==='free'?'Join for free':'Unlock for $2.99/month'}</button>{locked?.audience==='members'&&!signedIn&&<button className="text-link" onClick={()=>{setLocked(null);freeJoin();}}>Start with a free account</button>}</div></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={()=>setSelected(null)}><DialogContent className="modal post-modal"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.kind==='music'?'From the collection':'A little of what’s on my heart'}</DialogDescription></DialogHeader><div className="post-body">{selected?.body}</div>{selected?.mime?.startsWith('audio/')&&<audio controls preload="metadata" src={'/api/media/'+selected.id}/ >}{selected?.mime?.startsWith('video/')&&<video controls preload="metadata" src={'/api/media/'+selected.id}/ >}{selected?.mime?.startsWith('image/')&&<img alt={selected.title} src={'/api/media/'+selected.id}/ >}{selected?.audience==='public'&&!active&&<div className="offering-invitation"><p>If this found you, there’s more inside the circle.</p><a className="text-link" href="#membership" onClick={()=>setSelected(null)}>Explore the inner circle · $2.99/month</a></div>}</DialogContent></Dialog></>;
}
