"use client";
import { useState,useEffect } from 'react';
import MemberControls from './member-controls';
import { Music2,Lock,Headphones,Sparkles,Check,Flower2 } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
type Post={id:string;title:string;kind:string;audience:string;published:number;body?:string;mime?:string};
export default function Home({signedIn,active,owner,ready,posts,unavailable}:{signedIn:boolean;active:boolean;owner:boolean;ready:boolean;posts:Post[];unavailable:boolean}){
 const [tab,setTab]=useState('all'),[notice,setNotice]=useState(''),[selected,setSelected]=useState<Post|null>(null),[busy,setBusy]=useState(false);
 const join=async()=>{if(!ready){setNotice('The circle is opening soon. Membership will be $2.99 per month. Come back for the first release.');return;}if(!signedIn){location.href='/sign-in?redirect_url=%2F%23membership';return;}setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST'});const d:any=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url;}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
 const open=async(p:Post)=>{try{const r=await fetch('/api/posts/'+p.id);const d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(d);}catch(e){setNotice((e as Error).message);}};
 const portal=async()=>{try{const r=await fetch('/api/portal',{method:'POST'});const d:any=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url;}catch(e){setNotice((e as Error).message);}};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx)return;const a=new AbortController();Promise.resolve(ctx.registerTool({name:'browse_sarafina_library',description:'Filter the visible library by all, music, or journal.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['all','music','journal']}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async({category}:{category:string})=>{if(!['all','music','journal'].includes(category))throw Error('Invalid category');setTab(category);return {category,count:posts.filter(p=>category==='all'||p.kind===category).length};}},{signal:a.signal})).catch(()=>{});return ()=>a.abort();},[posts]);
 return <><header><a className="brand" href="/">SARAFINA <span>ETHEREAL</span></a><nav><a href="#library">The collection</a><a href="#membership">The inner circle</a>{owner&&<a href="/studio">Creator studio</a>}{signedIn?<MemberControls/>:<a href="/sign-in">Member sign in</a>}</nav></header>
 <main><section className="hero"><div className="portrait" role="img" aria-label="Sarafina Ethereal wearing an ornate floral and pearl crown"/><div className="hero-copy"><p className="eyebrow">A LITTLE CLOSER TO THE MUSIC</p><h1>Sarafina<br/><i>Ethereal.</i></h1><p className="intro">Soulful. Visceral. Unfiltered.<br/>A world of sound, and a place inside it for you.</p><button className="button" onClick={active?()=>document.getElementById('library')?.scrollIntoView():join} disabled={busy}>{active?'Enter your collection':'Join the inner circle'} <span>{active?<Headphones size={18}/>: '$2.99 / month'}</span></button><a className="text-link" href="#library">Explore the collection</a></div><div className="hero-bottom"><span>ORIGINAL MUSIC · INTIMATE MOMENTS</span><span>AN OFFERING, EVERY WEEK</span></div></section>
 <section className="library section" id="library"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Stay for a while.</h2></div><p>Old favorites. New beginnings.<br/>Music and moments from the world of Sarafina.</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="collection-tabs"><TabsTrigger value="all">Everything</TabsTrigger><TabsTrigger value="music">Music</TabsTrigger><TabsTrigger value="journal">Notes & moments</TabsTrigger></TabsList>{['all','music','journal'].map(t=><TabsContent key={t} value={t}><div className="post-grid">{posts.filter(p=>t==='all'||p.kind===t).map(p=><button className="post" key={p.id} onClick={()=>open(p)}><div className={'post-art '+p.kind}>{p.kind==='music'?<Music2 size={42}/>:<Flower2 size={42}/>}<span>{p.audience==='members'&&!active?<><Lock size={13}/> INNER CIRCLE</>:'OPEN TO EVERYONE'}</span></div><p className="post-meta">{p.kind==='music'?'MUSIC':'NOTES & MOMENTS'} · {new Date(p.published*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'})}</p><h3>{p.title}</h3></button>)}</div>{posts.filter(p=>t==='all'||p.kind===t).length===0&&<div className="empty"><Sparkles size={26}/><h3>{unavailable?'The collection is taking a moment.':'Something intimate is on its way.'}</h3><p>{unavailable?'Please refresh to try again.':'The first offerings will appear here. Members get the music archive and fresh content every week.'}</p></div>}</TabsContent>)}</Tabs><div className="collection-note"><Headphones size={20}/><p>Less distance between the artist and the listener.</p><span>Music · Process · Presence</span></div></section>
 <section className="membership section" id="membership"><div className="membership-copy"><p className="eyebrow">THE INNER CIRCLE</p><h2>The music.<br/>The moments.<br/><i>You, a little closer.</i></h2><p>A small monthly offering that supports independent music—and opens the door to more of it.</p></div><div className="membership-card"><Flower2 size={33}/><h3>A place in the circle</h3><p className="price">$2.99 <span>/ month</span></p><ul>{['Access to the music archive','New music and exclusive releases','Fresh content every week','Notes and moments behind the music'].map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul>{active?<button className="button" onClick={portal}>Manage membership</button>:<button className="button" onClick={join} disabled={busy}>{busy?'Opening checkout…':ready?'Become a member':'Join the inner circle'}</button>}<p className="fine">{ready?'Monthly membership. Cancel anytime. Payments handled securely by Stripe.':'Membership opens soon. $2.99 per month. Cancel anytime.'}</p></div></section>
 <section className="closing"><p className="eyebrow">ETHEREAL, BUT ALWAYS HUMAN.</p><p>For the ones who feel it all.</p><Flower2 size={25}/></section></main><footer><a className="brand" href="/">SARAFINA <span>ETHEREAL</span></a><span>Independent music. A shared world.</span><small>© {new Date().getFullYear()} Sarafina Ethereal</small></footer>
 <Dialog open={!!notice} onOpenChange={()=>setNotice('')}><DialogContent className="modal"><DialogHeader><DialogTitle>A little note</DialogTitle><DialogDescription>{notice}</DialogDescription></DialogHeader></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={()=>setSelected(null)}><DialogContent className="modal post-modal"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.kind==='music'?'From the collection':'A note from Sarafina'}</DialogDescription></DialogHeader><div className="post-body">{selected?.body}</div>{selected?.mime?.startsWith('audio/')&&<audio controls preload="metadata" src={'/api/media/'+selected.id}/ >}{selected?.mime?.startsWith('video/')&&<video controls preload="metadata" src={'/api/media/'+selected.id}/ >}{selected?.mime?.startsWith('image/')&&<img alt={selected.title} src={'/api/media/'+selected.id}/ >}</DialogContent></Dialog></>;
}
