CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY NOT NULL,email TEXT NOT NULL,customer TEXT UNIQUE,subscription TEXT UNIQUE,status TEXT NOT NULL DEFAULT 'inactive',updated INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,preview TEXT NOT NULL DEFAULT '',kind TEXT NOT NULL,audience TEXT NOT NULL,asset TEXT,mime TEXT,published INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS posts_published_idx ON posts(published DESC);
CREATE TABLE IF NOT EXISTS uploads (pathname TEXT PRIMARY KEY NOT NULL,owner TEXT NOT NULL,created INTEGER NOT NULL,completed INTEGER NOT NULL DEFAULT 0);
